<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120119134846 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE vs_timesheet_domain_model_customer ADD color VARCHAR(50) NOT NULL");
        $this->addSql("ALTER TABLE vs_timesheet_domain_model_project ADD color VARCHAR(50) NOT NULL");
		$this->addSql("ALTER TABLE vs_timesheet_domain_model_task ADD color VARCHAR(50) NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
        $this->addSql("ALTER TABLE vs_timesheet_domain_model_customer DROP color");
        $this->addSql("ALTER TABLE vs_timesheet_domain_model_project DROP color");
		$this->addSql("ALTER TABLE vs_timesheet_domain_model_task DROP color");
	}
}

?>