TYPO3:
  FLOW3:
    security:
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            provider: TYPO3\FLOW3\Security\Authentication\Provider\PersistedUsernamePasswordProvider
            providerOptions:
              entryPoint: 'WebRedirect'
              entryPointOptions:
                uri: 'standard/index'
      authorization:
        # An array of access decision voters that should vote when access decisions are made
        accessDecisionVoters:
          - TYPO3\FLOW3\Security\Authorization\Voter\Policy
    locale:
      defaultLocaleIdentifier: de
      defaultLocale: de
VS:
  TimeSheet:
    brand: TimeSheet
    version: "1.0.5"
    versionDate: "11. Mai 2012"
    weekdays:
      sunday: Sonntag
      monday: Montag
      tuesday: Dienstag
      wednesday: Mittwoch
      thursday: Donnerstag
      friday: Freitag
      saturday: Samstag
    formats:
      dateTime:
        full: 'l, d.m.Y'
        default: 'l, d.m.Y'