TYPO3:
  FLOW3:
    security:
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            providerClass: TYPO3\FLOW3\Security\Authentication\Provider\PersistedUsernamePasswordProvider
            entryPoint:
              WebRedirect:
                uri: standard/index
      authorization:
        # An array of access decision voters that should vote when access decisions are made
        accessDecisionVoters:
          - TYPO3\FLOW3\Security\Authorization\Voter\Policy
VS:
  TimeSheet:
    brand: TimeSheet
    version: "1.0.2"
    versionDate: "15. Januar 2012"
    weekdays:
      sunday: Sonntag
      monday: Montag
      tuesday: Dienstag
      wednesday: Mittwoch
      thursday: Donnerstag
      friday: Freitag
      saturday: Samstag
    formats:
      dateTime:
        full: 'd.m.Y'